In [1]:
# numpy is used for creating n-dimensional array
# install numpy
# from jupyter - !pip install numpy
# from cmd - python (or) py -m pip  install numpy

In [2]:
import numpy as np

a =  [1,2,3,4]

arr1 = np.array(a)

print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
b = [12,18,22,25]

arr2 = np.array(b)

print(arr1)

print(arr2)

[1 2 3 4]
[12 18 22 25]


In [4]:
# adding 2 lists results in concatenation
# adding 2 numpy array results in addition

c = a+b
print(c)

[1, 2, 3, 4, 12, 18, 22, 25]


In [5]:
arr3 = arr1+arr2 # adding numpy arrays

print(arr3)

[13 20 25 29]


In [6]:
# shape - numpy arrays attribute

arr1 = np.array(
    [1,2,3,4]
)

print(arr1.shape)

(4,)


In [7]:
arr1 = np.array(
    [
        [1,2,3,4],
        [12,18,22,25]
    ]
    
)
print(arr1.shape) # output will be (2,4) i.e., 2 rows and 4 columns

(2, 4)


In [8]:
arr1 = np.array([
    [
        [1,2,3,4],
        [12,18,22,25]
    ],
    [
        [1,2,3,4],
        [12,18,22,25]
    ],
    
    
])
print(arr1.shape) # output will be (2,2,4) i.e., 2 arrays and each array has 2 rows and 4 columns

(2, 2, 4)


In [9]:
# linspace - can be used for producing 'n' values between a very small range

arr = np.linspace(0,0.5,100)

print(arr)

[0.         0.00505051 0.01010101 0.01515152 0.02020202 0.02525253
 0.03030303 0.03535354 0.04040404 0.04545455 0.05050505 0.05555556
 0.06060606 0.06565657 0.07070707 0.07575758 0.08080808 0.08585859
 0.09090909 0.0959596  0.1010101  0.10606061 0.11111111 0.11616162
 0.12121212 0.12626263 0.13131313 0.13636364 0.14141414 0.14646465
 0.15151515 0.15656566 0.16161616 0.16666667 0.17171717 0.17676768
 0.18181818 0.18686869 0.19191919 0.1969697  0.2020202  0.20707071
 0.21212121 0.21717172 0.22222222 0.22727273 0.23232323 0.23737374
 0.24242424 0.24747475 0.25252525 0.25757576 0.26262626 0.26767677
 0.27272727 0.27777778 0.28282828 0.28787879 0.29292929 0.2979798
 0.3030303  0.30808081 0.31313131 0.31818182 0.32323232 0.32828283
 0.33333333 0.33838384 0.34343434 0.34848485 0.35353535 0.35858586
 0.36363636 0.36868687 0.37373737 0.37878788 0.38383838 0.38888889
 0.39393939 0.3989899  0.4040404  0.40909091 0.41414141 0.41919192
 0.42424242 0.42929293 0.43434343 0.43939394 0.44444444 0.44949

In [10]:
# initialise arrays with zeros

arr = np.zeros((3,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# initialise arrays with ones

arr = np.ones((3,4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
